load(":define_modules.bzl", "define_modules")
load("//build/kernel/kleaf:kernel.bzl", "ddk_headers")

define_modules("sdxkova", "perf")

define_modules("sdxkova", "debug")

define_modules("sdxkova.cpe.wkk", "perf")
define_modules("sdxkova.cpe.wkk", "debug")

define_modules("sdxkova.512", "perf")
define_modules("sdxkova.512", "debug")

define_modules("sdxkova.cpe.tarang", "perf")
define_modules("sdxkova.cpe.tarang", "debug")

define_modules("sdxkova.prpl", "perf")
define_modules("sdxkova.prpl", "debug")

package(
    default_visibility = [
      "//visibility:public",
    ],
)

ddk_headers(
    name = "ioss_headers",
    hdrs = glob([
        "drivers/ioss/ioss_i.h",
        "drivers/ioss/ioss_version.h",
        "drivers/ioss/include/linux/msm/ioss.h",
        "drivers/ioss/include/linux/msm/ioss_qos.h",
    ]),
    includes = [
        "drivers/ioss",
        "drivers/ioss/include/linux/msm",
    ],
)

ddk_headers(
    name = "rtl8125_headers",
    hdrs = glob([
        "drivers/rtl8125/src/r8125_firmware.h",
        "drivers/rtl8125/src/r8125_dash.h",
        "drivers/rtl8125/src/r8125_ptp.h",
        "drivers/rtl8125/src/r8125.h",
        "drivers/rtl8125/src/r8125_lib.h",
        "drivers/rtl8125/src/r8125_realwow.h",
        "drivers/rtl8125/src/r8125_rss.h",
        "drivers/rtl8125/src/rtl_eeprom.h",
        "drivers/rtl8125/src/rtltool.h",
    ]),
    includes = [
        "drivers/rtl8125",
        "drivers/rtl8125/src",
    ],
)

ddk_headers(
    name = "atlantic_fwd_headers",
    hdrs = glob([
        "drivers/atlantic_fwd/atl_common.h",
        "drivers/atlantic_fwd/atl_compat.h",
        "drivers/atlantic_fwd/atl_desc.h",
        "drivers/atlantic_fwd/atl_drviface.h",
        "drivers/atlantic_fwd/atl_dump.h",
        "drivers/atlantic_fwd/atl_ethtool.h",
        "drivers/atlantic_fwd/atl_fw.h",
        "drivers/atlantic_fwd/atl_fwd.h",
        "drivers/atlantic_fwd/atl_hw.h",
        "drivers/atlantic_fwd/atl_hw_ptp.h",
        "drivers/atlantic_fwd/atl_log.h",
        "drivers/atlantic_fwd/atl_mdio.h",
        "drivers/atlantic_fwd/atl_ptp.h",
        "drivers/atlantic_fwd/atl_regs.h",
        "drivers/atlantic_fwd/atl_ring.h",
        "drivers/atlantic_fwd/atl_ring_desc.h",
        "drivers/atlantic_fwd/atl_stats.h",
        "drivers/atlantic_fwd/atl_trace.h",
        "drivers/atlantic_fwd/atl2_fw.h",
        "drivers/atlantic_fwd/atl_fwdnl.h",
        "drivers/atlantic_fwd/atl_macsec.h",
    ]),
    includes = [
        "drivers/atlantic_fwd",
    ],
)
