M=$(PWD)
DATAETH_ROOT=$(KERNEL_SRC)/$(M)

KBUILD_OPTIONS+=KBUILD_DTC_INCLUDE=$(DATAETH_ROOT)

all: modules # dtbs

clean:
	$(MAKE) -C $(KERNEL_SRC) M=$(M) clean

%:
	$(MAKE) -C $(KERNEL_SRC) M=$(M) $@ $(KBUILD_OPTIONS)
