#! /bin/bash
# Copyright (c) 2020-2021, The Linux Foundation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#     * Neither the name of The Linux Foundation nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
# ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
# OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
# IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#Changes from Qualcomm Innovation Center, Inc. are provided under the following license:
#Copyright (c) 2025 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

echo "eth_cli.sh is started" > /dev/kmsg
# handle ID for eth0
mq0_handle_id=100
exit_status=0

del_tc() {
    # eth_cli.sh del <dev> <mqprio/filter/all>
    local dev_name=$1
    local tc_commands=""
    shift
    if [ "$1" == "mqprio" ]
    then
        # tc qdisc delete dev eth0 handle 100: parent root mqprio
        shift
        tc_commands="qdisc delete dev $dev_name handle $mq0_handle_id: parent root mqprio"
        /sbin/tc $tc_commands
        exit_status=$?
        if [ $exit_status -ne 0 ]
        then
            echo "TC command couldn't be executed successfully, Please check if mqprio configuration is there or not."
            return 255
        fi
    elif [ "$1" == "filter" ]
    then
        # tc filter del dev eth0 egress
        tc_commands="filter del dev $dev_name egress"
        /sbin/tc $tc_commands
        exit_status=$?
        if [ $exit_status -ne 0 ]
        then
            echo "TC command couldn't be executed successfully, please refer to help page and retry it."
            return 255
        fi
    elif [ "$1" == "all" ]
    then
        shift
        tc_commands="qdisc delete dev $dev_name handle $mq0_handle_id: parent root mqprio"
        echo $tc_commands
        /sbin/tc $tc_commands
        exit_status=$?
        if [ $exit_status -ne 0 ]
        then
            echo "Failed to delete mqprio cbs sfq. Please check if mqprio configuration is there or not. "
            echo "Filter del don't have chance to be executed."
            return 255
        fi
    else
        echo "There is no $1 parameter for delete action. Please refer to help page."
    fi
}

add_tc() {
    if [ $# -lt 1 ]
    then
        print_usage
        return 255
    fi
    local tc_commands=""
    local dev_name=$1
    local cbs_handle_id=""
    local sfq=""

    shift
    if [ "$1" == "mqprio" ]
    then
        shift
        if [ $# -lt 1 ]
        then
            print_usage
            return 255
        fi
        mq0_handle_id=$1
        if [ $mq0_handle_id -lt 1 ]
        then
            echo "Mqprio handle ID is not invalid. it should be more than 0."
        fi
        shift
        map_prio=$@
        if [ $# -gt 16 ]
        then
            echo "Illegal number of parameters, the max is 16."
            return 255
        fi
        #check if the map_prio is invalid or not.
        for var in $map_prio
        do
            if [ $var -gt 5 ] || [ $var -lt 0 ]
            then
                echo "Prio mapping value couldn't bigger than 5 or less than 0."
                return 255
            fi
        done
        tc_commands="qdisc add dev $dev_name handle $mq0_handle_id: parent root mqprio num_tc 5 map $map_prio queues 1@1 1@2 1@3 1@4 1@5 hw 0"
        echo $tc_commands
        /sbin/tc $tc_commands
        exit_status=$?
        if [ $exit_status -ne 0 ]
        then
            echo "TC command couldn't be executed successfully, please refer to help page and retry it."
            echo "Hint: Once the mqprio is already existed, we couldn't configure it again. Please delete it firstly."
            return 255
        fi
        # Once create mqprio, so adding gptp as well.
        /sbin/tc filter add dev "$dev_name" egress prio 0 u32 match u16 0x88f7 0xffff at -2 action skbedit priority 4
    elif [ "$1" == "cbs" ]
    then
        shift
        if [ $# -lt 2 ]
        then
            echo "Parameter is invalid. Please refer to help page."
            return 255
        fi
        cbs_handle_id=$1
        if [ $cbs_handle_id -lt 1 ] || [ $cbs_handle_id -eq $mq0_handle_id ]
        then
            echo "Cbs handle ID is not invalid. It should be more than 0 and couldn't be same as maqprio handle ID."
            return 255
        fi
        shift
        queue=$1
        # check if the queue is invalid or not.
        if [ $queue -gt 5 ] || [ $queue -lt 2 ]
        then
            echo "The max queue value is >= 2 and <= 5."
            return 255
        fi
        shift
        tc_commands="qdisc replace dev $dev_name handle $cbs_handle_id parent $mq0_handle_id:$queue cbs "
        while [ $# -gt 0 ]
        do
            if [ "$1" == "idleslope" ]
            then
                shift
                # check $1 numbers. to > 1000 and < 1000 0000
                if [ $# -lt 1 ]
                then
                    echo "Parameter is missing. Please refer to help page."
                    return 255
                fi
                if [ "$1" -lt 1000 ] || [ "$1" -gt 1000000 ]
                then
                    echo "The value should be >= 1000 and <= 1000000."
                    return 255
                fi
                tc_commands="$tc_commands idleslope $1"
            elif [ "$1" == "sendslope" ]
            then
                shift
                if [ $# -lt 1 ]
                then
                    echo "Parameter is missing. Please refer to help page."
                    return 255
                fi
                if [ $1 -gt -1000 ] || [ $1 -lt -1000000 ]
                then
                    echo "The value should be <= -1000 and >= -1000000."
                    return 255
                fi
                tc_commands="$tc_commands sendslope $1"
            elif [ $1 == "hicredit" ]
            then
                shift
                if [ $# -lt 1 ]
                then
                    echo "Parameter is missing. Please refer to help page."
                    return 255
                fi
                if [ $1 -le 0 ]
                then
                    echo "The value should be > 0."
                    return 255
                fi
                tc_commands="$tc_commands hicredit $1"
            elif [ $1 == "locredit" ]
            then
                shift
                if [ $# -lt 1 ]
                then
                    echo "Parameter is missing. Please refer to help page."
                    return 255
                fi
                if [ $1 -ge 0 ]
                then
                    echo "The value should be < 0."
                    return 255
                fi
                tc_commands="$tc_commands locredit $1"
            elif [ $1 == "offload" ]
            then
                shift
                if [ $# -lt 1 ]
                then
                   echo "Parameter is missing. Please refer to help page."
                   return 255
                fi
                if [ $1 -eq 0 ] || [ $1 -eq 1 ]
                then
                   tc_commands="$tc_commands offload $1"
                else
                   echo "The value of Offload should be  0 or 1."
                   return 255
                fi
	    elif [ $1 == "sfq" ]
            then
                shift
                if [ $# -lt 1 ]
                then
                   echo "Parameter is missing. Please refer to help page."
                   return 255
                fi
                if [ $1 -eq 0 ] || [ $1 -eq 1 ]
                then
                   sfq=$1
                else
                   echo "The value of SFQ should be  0 or 1."
                   return 255
                fi
	        else
                   echo "$1 is not valid parameter."
                   return 255
                fi
            shift
        done
        echo $tc_commands
        /sbin/tc $tc_commands
        exit_status=$?
        if [ $exit_status -ne 0 ]
        then
            echo "TC command couldn't be executed successfully, please refer to help page and retry it."
            return 255
        fi
        if [ $sfq -eq 1 ]
        then
           # Configure the sfq as well.
           tc_commands="qdisc add dev $dev_name parent $cbs_handle_id:$queue sfq"
           echo $tc_commands
           /sbin/tc $tc_commands
        fi
        return $exit_status
    elif [ "$1" == "filter" ]
    then
        shift
        tc_commands="filter add dev $dev_name egress "
        while [ $# -gt 0 ]
        do
            if [ "$1" == "prio" ]
            then
                shift
                if [ $# -lt 1 ]
                then
                    echo "Parameter is missing. Please refer to help page."
                    return 255
                fi
                if [ $1 -lt 0 ] || [ $1 -gt 15 ]
                then
                    echo "The value should be >=0 and <=15."
                    return 255
                fi
                tc_commands="$tc_commands prio $1"
                shift
            elif [ "$1" == "ipsrc" ]
            then
                shift
                if [ $# -lt 1 ]
                then
                    echo "Parameter is missing. Please refer to help page."
                    return 255
                fi
                tc_commands="$tc_commands u32 match ip src $1"
                shift
	    elif [ "$1" == "priority" ]
            then
                shift
                if [ $# -lt 1 ]
                then
                    echo "Parameter is missing. Please refer to help page."
                    return 255
                fi
                if [ $1 -gt 15 ] || [ $1 -lt 0 ]
                then
                    echo "$1 is not valid parameter. Priority should be >= 0 and <= 15."
                    return 255
                fi
                tc_commands="$tc_commands action skbedit priority $1"
                shift
            else
                echo "$1 is not invalid parameter."
                return 255
            fi
        done
        echo $tc_commands
        /sbin/tc $tc_commands
        exit_status=$?
        if [ $exit_status -ne 0 ]
        then
            echo "TC command couldn't be executed successfully, please refer to help page and retry it."
            return 255
        fi
    elif [ "$1" == "clsact" ]
    then
        /sbin/tc qdisc add dev $dev_name clsact
    else
        echo "There is no $1 parameter for add action. Please refer to help page."
    fi
}

add_default_tc() {
        /sbin/tc qdisc add dev eth0 handle 100: parent root mqprio num_tc 5  map 0 1 2 3 4 queues 1@1 1@2 1@3 1@4 1@5 hw 0

        echo 1 > /sys/class/net/eth0/ethqos/tc_queue_select

        /sbin/tc qdisc replace dev eth0 handle 250 parent 100:5 cbs idleslope  10000 sendslope -990000 hicredit 8 locredit -1503 offload 1
        /sbin/tc qdisc add dev eth0 parent 250:5 sfq

        /sbin/tc qdisc replace dev eth0 handle 240 parent 100:4 cbs  idleslope 30000 sendslope -970000 hicredit 46 locredit -1472  offload 1
        /sbin/tc qdisc add dev eth0 parent 240:4 sfq

        /sbin/tc qdisc replace dev eth0 handle 230 parent 100:3 cbs idleslope 30000 sendslope -970000 hicredit 46 locredit -1472  offload 1
        /sbin/tc qdisc add dev eth0 parent 230:3 sfq

        /sbin/tc qdisc add dev eth0 clsact
        #PTP filter with Queue=5
        /sbin/tc filter add dev eth0 egress prio 0 u32 match u16 0x88f7 0xffff at -2 action skbedit priority 4

        /sbin/tc filter add dev eth0 egress prio 0 u32 match ip src 192.168.114.2 action skbedit priority 3
        /sbin/tc filter add dev eth0 egress prio 0 u32 match ip src 192.168.183.1 action skbedit priority 3
        /sbin/tc filter add dev eth0 egress prio 1 u32 match ip src 192.168.11.2 action skbedit priority 2
        /sbin/tc filter add dev eth0 egress prio 1 u32 match ip src 192.168.139.2 action skbedit priority 2
}
print_usage() {
    echo "
Usage:
    eth-cli add <dev> <op> [optional params]
    eg: eth-cli add eth0 mqprio 100 0 1 2 3 4
         100 : Handle
         0 1 2 3 4 : tc to prio map values
    eg: eth-cli add eth0 cbs 200 3 idleslope 98688  sendslope -901312  hicredit 153  locredit -1389 offload <0|1> sfq <0|1>
         200 : cbs handle to the qdisc or class
         3 : selects the queue which index start from 1. [3 here is mapped to Q2]
    eg: eth-cli add eth0 filter prio 2 ipsrc 192.168.114.2 priority 3
    eg: eth-cli add eth0 clsact
    eth-cli del <dev> <all>
    eth-cli show <dev>
    eth-cli tc_support <dev> <enable|disable>
    "
}

show_tc() {
    if [ $# -lt 1 ]
    then
        print_usage
        return 255
    fi
    local dev_name=$1
    shift
    /sbin/tc -s qdisc show dev $dev_name
    exit_status=$?
    if [ $exit_status -ne 0 ]
    then
        echo "Tc qdisc couldn't be executed successfully."
        return 255
    fi
    /sbin/tc -s filter show dev $dev_name egress
    exit_status=$?
    if [ $exit_status -ne 0 ]
    then
        echo "TC filter show couldn't be executed successfully."
        return 255
    fi
}

tc_support_enable() {
    if [ $# -lt 1 ]
    then
        print_usage
        return 255
    fi
    local dev_name=$1
    shift
    local config=$1
    if [ $config = "enable" ]
    then
        echo 1 > /sys/class/net/"$dev_name"/ethqos/tc_queue_select
        exit_status=$?
        if [ $exit_status -ne 0 ]
        then
            echo "TC support is not enabled"
        return 255
        fi
    elif  [ $config = "disable" ]
    then
         echo 0 > /sys/class/net/"$dev_name"/ethqos/tc_queue_select
        exit_status=$?
        if [ $exit_status -ne 0 ]
        then
            echo "TC support is not disabled"
        return 255
        fi
    else
        print_usage
        return 255
    fi
}

main() {
    if [ $# -lt 1 ]
    then
        print_usage
        return 255
    fi
    if [ "$1" == "add" ]
    then
        shift
        add_tc $@
    elif [ "$1" == "del" ]
    then
        shift
        del_tc $@
    elif [ "$1" == "default_qos" ]
    then
        add_default_tc
    elif [ "$1" == "show" ]
    then
        shift
        show_tc $@
    elif [ "$1" == "tc_support" ]
    then
        shift
        tc_support_enable $@
    else
        print_usage
    fi
}

main $@

echo "eth-cli.sh is executed successfully\n" > /dev/kmsg
