ccflags-y	+= $(COPTS)

obj-m := tc956x_pcie_eth.o
tc956x_pcie_eth-y := tc956xmac_main.o \
		tc956xmac_ethtool.o \
		tc956xmac_mdio.o \
		mmc_core.o \
		tc956xmac_hwtstamp.o \
		tc956xmac_ptp.o \
		tc956x_xpcs.o \
		tc956x_pma.o \
              	hwif.o \
	      	tc956xmac_tc.o \
		dwxgmac2_core.o \
        	dwxgmac2_descs.o \
		dwxgmac2_dma.o \
		tc956x_pci.o \
              	tc956x_msigen.o \
              	tc956x_pcie_logstat.o \
		tc956x_pf_rsc_mng.o \
              	tc956x_qcom.o
