obj-m += ethdbg.o
ethdbg-y := ethdbg_main.o
ethdbg-y += ethdbg_uio.o
ethdbg-y += ethdbg_dump.o
ethdbg-$(CONFIG_QCOM_MINIDUMP) += ethdbg_minidump.o
ethdbg-$(CONFIG_QCOM_MINIDUMP) += ethdbg_stmmac.o

ccflags-y += -I$(KERNEL_SRC)/drivers/net/ethernet/stmicro/stmmac
